fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class: App\Entity\Group
    from_email:
        address: "noreplay@cinecubano.online"
        sender_name: "Cine Cubano Online"