vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: '%app.path.user_avatar%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_avatar%'
            namer:              vich_uploader.namer_uniqid    
            directory_namer:    ~    
            delete_on_remove:   true 
            inject_on_load:     true
            delete_on_update:   true
        company_logo:
            uri_prefix: '%app.path.company_logo%'
            upload_destination: '%kernel.project_dir%/public%app.path.company_logo%'
            namer:              vich_uploader.namer_uniqid    
            directory_namer:    ~    
            delete_on_remove:   true 
            inject_on_load:     true
            delete_on_update:   true
