version: '3.7'

services:
  db:
    container_name: cart_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./var/mysql:/var/lib/mysql
  node:
    container_name: cart_node
    image: node
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
#      - ./.npmrc:/home/node/.npmrc
#      - ./.npmrc:/root/.npmrc
    tty: true
  app:
    container_name: cart_app
    build: .docker/app
    ports:
      - 8080:80
#    restart: none
    volumes:
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www:cached
    depends_on:
      - db
      - node
      - mailhog
    links:
      - db
      - node
      - mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: cart_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
